In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.1.0-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting numpy>=2.0.2 (from pandas)
  Downloading numpy-2.5.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\users\perfect\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.6-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\perfect\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp313-cp313-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.7 MB 1.2 MB/s eta 0:00:09
   - -------------------------------------- 0.5/10.7 MB 1.2 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/10.7 MB 945.3 kB/s eta 0:00:11
   --- ------------------------------------ 1.0/10.7 MB 920.0 kB/s eta 0:00:11
   --- ------------------------------------ 1.0/10.7 MB 920.0 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/10.7 MB 908.9 kB/s eta 0:00:11
   ---- ----------------------------------- 1.3/10.7 MB 908.9 kB/s eta 0:00:11
   ----- ---------------------------------- 1.6/10.7 MB 834.2 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/10.7 MB 838.7 kB/s eta 0:00:11
   ------- -------------------------------- 2.1/10.7 MB 860.2 kB/s eta 0:00:11
   ------- -------------------------------- 2.1/10.7 MB 860.2 kB/s eta 0:00:11
   -------- ------------------------------- 2.4/10.7 MB 856.7 kB/s eta 0:00:10
   --------- ------------------------------ 2.6/10.7 MB 843.0 kB/s eta 0:00:10
   --------- ------------------------------ 2.6/10.7 MB 843.0 kB/s eta 0:00:10
   ---------- ----------------------------- 2.9/10.7 MB 831.5 kB/s eta 0:00:10
   ---------- ----------------------------- 2.9/10.7 MB 831.5 kB/s eta 0:00:10
   ----------- ---------------------------- 3.1/10.7 MB 824.7 kB/s eta 0:00:10
   ------------ --------------------------- 3.4/10.7 MB 833.8 kB/s eta 0:00:09
   ------------ --------------------------- 3.4/10.7 MB 833.8 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/10.7 MB 837.7 kB/s eta 0:00:09
   ------------- -------------------------- 3.7/10.7 MB 837.7 kB/s eta 0:00:09
   -------------- ------------------------- 3.9/10.7 MB 805.4 kB/s eta 0:00:09
   --------------- ------------------------ 4.2/10.7 MB 826.3 kB/s eta 0:00:08
   ---------------- ----------------------- 4.5/10.7 MB 826.2 kB/s eta 0:00:08
   ---------------- ----------------------- 4.5/10.7 MB 826.2 kB/s eta 0:00:08
   ----------------- ---------------------- 4.7/10.7 MB 822.0 kB/s eta 0:00:08
   ----------------- ---------------------- 4.7/10.7 MB 822.0 kB/s eta 0:00:08
   ------------------ --------------------- 5.0/10.7 MB 819.0 kB/s eta 0:00:08
   ------------------- -------------------- 5.2/10.7 MB 826.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.2/10.7 MB 826.6 kB/s eta 0:00:07
   -------------------- ------------------- 5.5/10.7 MB 828.2 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/10.7 MB 832.0 kB/s eta 0:00:06
   ---------------------- ----------------- 6.0/10.7 MB 835.8 kB/s eta 0:00:06
   ---------------------- ----------------- 6.0/10.7 MB 835.8 kB/s eta 0:00:06
   ----------------------- ---------------- 6.3/10.7 MB 841.8 kB/s eta 0:00:06
   ------------------------ --------------- 6.6/10.7 MB 844.9 kB/s eta 0:00:05
   ------------------------ --------------- 6.6/10.7 MB 844.9 kB/s eta 0:00:05
   ------------------------ --------------- 6.6/10.7 MB 844.9 kB/s eta 0:00:05
   ------------------------- -------------- 6.8/10.7 MB 811.8 kB/s eta 0:00:05
   -------------------------- ------------- 7.1/10.7 MB 822.5 kB/s eta 0:00:05
   -------------------------- ------------- 7.1/10.7 MB 822.5 kB/s eta 0:00:05
   --------------------------- ------------ 7.3/10.7 MB 810.5 kB/s eta 0:00:05
   --------------------------- ------------ 7.3/10.7 MB 810.5 kB/s eta 0:00:05
   --------------------------- ------------ 7.3/10.7 MB 810.5 kB/s eta 0:00:05
   --------------------------- ------------ 7.3/10.7 MB 810.5 kB/s eta 0:00:05
   ----------------------------- ---------- 7.9/10.7 MB 799.1 kB/s eta 0:00:04
   ------------------------------- -------- 8.4/10.7 MB 825.4 kB/s eta 0:00:03
   -------------------------------- ------- 8.7/10.7 MB 835.1 kB/s eta 0:00:03
   -------------------------------- ------- 8.7/10.7 MB 835.1 kB/s eta 0:00:03
   --------------------------------- ------ 8.9/10.7 MB 842.9 kB/s eta 0:00:03
   ---------------------------------- ----- 9.2/10.7 MB 836.9 kB/s eta 0:00:02
   ---------------------------------- ----- 9.2/10.7 MB 836.9 kB/s eta 0:00:02
   ----------------------------------- ---- 9.4/10.7 MB 836.2 kB/s eta 0:00:02
   ------------------------------------ --- 9.7/10.7 MB 842.8 kB/s eta 0:00:02
   ------------------------------------- -- 10.0/10.7 MB 846.6 kB/s eta 0:00:01
   -------------------------------------- - 10.2/10.7 MB 851.4 kB/s eta 0:00:01
   -------------------------------------- - 10.2/10.7 MB 851.4 kB/s eta 0:00:01
   ---------------------------------------  10.5/10.7 MB 856.2 kB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 854.6 kB/s  0:00:12
Downloading numpy-2.5.4-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 799.3 kB/s eta 0:00:16
   - -------------------------------------- 0.5/12.6 MB 799.3 kB/s eta 0:00:16
   - -------------------------------------- 0.5/12.6 MB 799.3 kB/s eta 0:00:16
   - -------------------------------------- 0.5/12.6 MB 799.3 kB/s eta 0:00:16
   - -------------------------------------- 0.5/12.6 MB 799.3 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.6 MB 430.3 kB/s eta 0:00:28
   ---- ----------------------------------- 1.3/12.6 MB 684.5 kB/s eta 0:00:17
   ----- ---------------------------------- 1.6/12.6 MB 769.4 kB/s eta 0:00:15
   ----- ---------------------------------- 1.8/12.6 MB 792.5 kB/s eta 0:00:14
   ----- ---------------------------------- 1.8/12.6 MB 792.5 kB/s eta 0:00:14
   ------ --------------------------------- 2.1/12.6 MB 787.1 kB/s eta 0:00:14
   ------- -------------------------------- 2.4/12.6 MB 815.3 kB/s eta 0:00:13
   -------- ------------------------------- 2.6/12.6 MB 856.4 kB/s eta 0:00:12
   --------- ------------------------------ 2.9/12.6 MB 886.5 kB/s eta 0:00:11
   --------- ------------------------------ 2.9/12.6 MB 886.5 kB/s eta 0:00:11
   ---------- ----------------------------- 3.4/12.6 MB 907.3 kB/s eta 0:00:11
   ----------- ---------------------------- 3.7/12.6 MB 934.3 kB/s eta 0:00:10
   ------------ --------------------------- 3.9/12.6 MB 960.7 kB/s eta 0:00:09
   ------------- -------------------------- 4.2/12.6 MB 966.0 kB/s eta 0:00:09
   -------------- ------------------------- 4.5/12.6 MB 974.2 kB/s eta 0:00:09
   --------------- ------------------------ 4.7/12.6 MB 964.3 kB/s eta 0:00:09
   --------------- ------------------------ 4.7/12.6 MB 964.3 kB/s eta 0:00:09
   --------------- ------------------------ 5.0/12.6 MB 944.1 kB/s eta 0:00:09
   ---------------- ----------------------- 5.2/12.6 MB 960.7 kB/s eta 0:00:08
   ----------------- ---------------------- 5.5/12.6 MB 973.3 kB/s eta 0:00:08
   ----------------- ---------------------- 5.5/12.6 MB 973.3 kB/s eta 0:00:08
   ------------------ --------------------- 5.8/12.6 MB 958.1 kB/s eta 0:00:08
   ------------------- -------------------- 6.0/12.6 MB 947.5 kB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.6 MB 947.5 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.6 MB 937.7 kB/s eta 0:00:07
   -------------------- ------------------- 6.6/12.6 MB 936.1 kB/s eta 0:00:07
   -------------------- ------------------- 6.6/12.6 MB 936.1 kB/s eta 0:00:07
   --------------------- ------------------ 6.8/12.6 MB 943.8 kB/s eta 0:00:07
   ---------------------- ----------------- 7.1/12.6 MB 935.0 kB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.6 MB 935.0 kB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.6 MB 935.0 kB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.6 MB 935.0 kB/s eta 0:00:06
   ------------------------ --------------- 7.6/12.6 MB 910.1 kB/s eta 0:00:06
   ------------------------- -------------- 7.9/12.6 MB 916.1 kB/s eta 0:00:06
   ------------------------- -------------- 8.1/12.6 MB 911.2 kB/s eta 0:00:05
   ------------------------- -------------- 8.1/12.6 MB 911.2 kB/s eta 0:00:05
   -------------------------- ------------- 8.4/12.6 MB 914.7 kB/s eta 0:00:05
   --------------------------- ------------ 8.7/12.6 MB 919.8 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.6 MB 921.6 kB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.6 MB 921.6 kB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.6 MB 921.6 kB/s eta 0:00:04
   ----------------------------- ---------- 9.2/12.6 MB 900.4 kB/s eta 0:00:04
   ----------------------------- ---------- 9.2/12.6 MB 900.4 kB/s eta 0:00:04
   ------------------------------ --------- 9.4/12.6 MB 878.8 kB/s eta 0:00:04
   ------------------------------ --------- 9.7/12.6 MB 891.3 kB/s eta 0:00:04
   ------------------------------ --------- 9.7/12.6 MB 891.3 kB/s eta 0:00:04
   ------------------------------- -------- 10.0/12.6 MB 889.0 kB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.6 MB 892.8 kB/s eta 0:00:03
   --------------------------------- ------ 10.5/12.6 MB 894.4 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.6 MB 897.3 kB/s eta 0:00:03
   ---------------------------------- ----- 10.7/12.6 MB 897.3 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.6 MB 899.3 kB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 902.1 kB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 906.4 kB/s eta 0:00:02
   ------------------------------------- -- 11.8/12.6 MB 909.2 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 912.7 kB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 912.7 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 913.2 kB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 909.6 kB/s  0:00:13
Downloading tzdata-2026.6-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.4 pandas-3.1.0 tzdata-2026.6
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Perfect\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Pass either list of TUPPLE
# index=None, dtype=None, name=None

import pandas as pd
Data_01 = (1,2,3,4,5)
Series  = pd.Series(Data_01)
Series

ImportError: numpy._core.multiarray failed to import

In [5]:
import pandas as pd

Data_01 = (1, 2, 3, 4, 5)

Series = pd.Series(Data_01)

print(Series)

ImportError: numpy._core.multiarray failed to import

In [6]:
import sys
print(sys.executable)

c:\Users\Perfect\AppData\Local\Programs\Python\Python313\python.exe

In [7]:
import numpy as np

print("NumPy:", np.__version__)
print("NumPy path:", np.__file__)

NumPy: 2.5.4
NumPy path: c:\Users\Perfect\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__init__.py

In [8]:
import pandas as pd

Data_01 = (1, 2, 3, 4, 5)

Series = pd.Series(Data_01)

print(Series)

ImportError: numpy._core.multiarray failed to import

In [1]:
import pandas as pd

print("Pandas:", pd.__version__)

Pandas: 3.1.0

In [2]:
import pandas as pd

Data_01 = (1, 2, 3, 4, 5)

Series = pd.Series(Data_01)

print(Series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
# Using Dict, you will get index as well of your choice
Data_01 = {"KEY_1":1,"KEY_2":2,"KEY_3":3}
Data_01
pd.Series(Data_01)

KEY_1    1
KEY_2    2
KEY_3    3
dtype: int64

In [4]:
# Create the Series uisng Dictinary Pandas
calories = {"day1": 420, "day2": 380, "day3": 390}
calSeries = pd.Series(calories,)
calSeries

day1    420
day2    380
day3    390
dtype: int64

In [5]:
new_Dict = {'Name':["Rajesh","Sunil","Prakash"],
            "Age":[20,30,40]}

df = pd.DataFrame(new_Dict)
df

      Name  Age
0   Rajesh   20
1    Sunil   30
2  Prakash   40

In [6]:
# Create Dataframe from Dictionary
data = {"calories" : [420, 380, 390],
        "duration" : [50,  40,   45]}
df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [7]:
# Create Dataframe from List
listInsideLIST =  [ ["Alice", 25],
                   ["Bob", 30],
                   ["Charlie", 22],
                   ["David", 35]   ]
pd.DataFrame(listInsideLIST,columns=['Name',"Age"])

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35

In [2]:
import pandas as pd

newDict = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 22, 35]
}

pd.DataFrame(newDict)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35

In [1]:
import pandas as pd

newDict = {
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 22, 35]
}

pd.DataFrame(newDict)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   35

In [2]:
# Create the Series uisng Dictinary Pandas
calories = {"day1": 420, "day2": 380, "day3": 390}
calSeries = pd.Series(calories,)
calSeries

day1    420
day2    380
day3    390
dtype: int64